### ISSUE TITLE
summarize and run stats at the level of sample

### ISSUE THREAD

**Issue by hputnam** [daniellembecker/A.pul_Heatwave#1]
@daniellembecker For eggs per bundle and egg size, etc you need to take the mean of the counts you did for each parent sample and then run the stats on that sample size. By running them on 24 replicates per colony for eggs per bundle, you are artificially inflating the sample size and influencing the stats

Check this for every response variable where you have multiple counts per adult fragment or adult colony

**Comment by daniellembecker** [comment]
completed for egg size and eggs per bundle, figure 5

[Figure 5](https://docs.google.com/document/d/1UJn59j_gmjUJfIXBUfqyffPxT8fK6fwUxuqIq-v0Yzk/edit)
