### ISSUE TITLE
Inconsistent alignment rates between hisat2 aligner and bowtie2 aligner in RSEM 

### ISSUE THREAD

**Issue by daniellembecker** [daniellembecker/A.pul_Heatwave#4]
Hi Hollie,

I am currently working through an issue I noticed between using different aligners for aligning our A. pul heatwave samples to the reference transcriptome. Here is my workflow:

[sample workflow](https://github.com/daniellembecker/DanielleBecker_Lab_Notebook/blob/master/_posts/2023-01-01-A.pulchra-RNASeq-Workflow.md)

When I originally ran hisat2 outside of the Trinity RSEM and bowtie2 for mapping to the reference transcriptome, I was getting ~80% mapping to the reference, however when I used bowtie2 in the Trinty RSEM pipeline, I was getting around ~40%. I have been trying to troubleshoot and look into specific documentation into why this may be occurring, as well as, looking into the transcriptome assembly which has checked out in the statistical steps for N50 stats and checking quality with BUSCO which all checked out with the literature and assembly steps.

Alignment outputs for hisat2:

![Screen Shot 2024-08-19 at 4 32 11 PM](https://github.com/user-attachments/assets/57d7fb8c-7102-4be0-bb50-65c342f08b0d)

Alignment outputs for bowtie2 in RSEM pipeline:

![Screen Shot 2024-08-19 at 4 03 50 PM](https://github.com/user-attachments/assets/9cca515c-b1c4-4361-b760-3cf867902865)

I have found through documentation that RSEM cannot handle discordant reads that hisat2 can, which through literature say are still valuable to keep for downstream analysis. Wondering your thoughts and if we can discuss next steps!

**Comment by hputnam** [comment]
What do you mean by  "hisat2 outside of the Trinity RSEM and bowtie2 for mapping" versus "Inside"?

**Comment by hputnam** [comment]
Why can't you use hisat2?

**Comment by daniellembecker** [comment]
You can also use hisat2 as an alignment method within the Trinity RSEM pipeline so just wanted to clarify it was not a method used within it. 

I can use hisat2, Trinity and RSEM is suggested to streamline the process to make the gene and isoform matrices all in one step but it cannot handle discordant reads so that is where the discrepancies are I think from looking into the documentation.

**Comment by hputnam** [comment]
What are your data indicating discordant reads? If you have data supporting or suggesting discordant reads and one of your workflows cannot handle that, then use the one that is designed to handle it.

**Comment by hputnam** [comment]
Is this an issue that you need help with still, or is this just a result of two different aligners working in different ways?

**Comment by daniellembecker** [comment]
Nope all good, just was a result of the aligners working in different ways and just wanted your thoughts on!
